preprocessing:
  downsample_frequency: 900
  notch_frequencies: [50,100,150,200]
  tfr_subsampling_factor: 60
  tfr_logspace_low: 0.3010299956639812
  tfr_logspace_high: 2.4771212547196626
  tfr_logspace_nr: 200

trigger_channels: 'DC'
trigger_threshold: 1
non_data_channels: ['ECG', 'DELT', 'EEG']
non_data_channel_types: ['ecg', 'emg', 'eeg']
trigger_channel_names: ['DC09', 'DC10', 'DC11', 'DC12', 'DC13','DC14','DC15','DC16']
task: 'pRF'
acquisition_types: ['10kHz', '10kHz', '2kHz', '2kHz', '2kHz', '2kHz']
nr_runs: 6
nr_jobs: 32
